In [1]:
import pandas as pd

df = pd.read_csv("../dataset/raw/expense_dataset.csv")

df.head()

                        date    category  amount
0  2022-07-06 05:57:10 +0000  Restuarant    5.50
1  2022-07-06 05:57:27 +0000      Market    2.00
2  2022-07-06 05:58:12 +0000       Coffe   30.10
3  2022-07-06 05:58:25 +0000      Market   17.33
4  2022-07-06 05:59:00 +0000  Restuarant    5.50

In [2]:
df.shape

(4597, 3)

In [3]:
df.columns

Index(['date', 'category', 'amount'], dtype='object')

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4597 entries, 0 to 4596
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   date      4597 non-null   object
 1   category  4597 non-null   object
 2   amount    4597 non-null   float64
dtypes: float64(1), object(2)
memory usage: 107.9+ KB

In [5]:
df.describe()

            amount
count  4597.000000
mean     15.591100
std      75.778464
min       0.050000
25%       4.000000
50%       7.100000
75%      11.500000
max    2500.000000

In [6]:
df["date"] = pd.to_datetime(df["date"])

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4597 entries, 0 to 4596
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   date      4597 non-null   datetime64[ns, UTC]
 1   category  4597 non-null   object
 2   amount    4597 non-null   float64
dtypes: datetime64[ns, UTC](1), float64(1), object(1)
memory usage: 107.9+ KB

In [8]:
df["year"] = df["date"].dt.year
df["month"] = df["date"].dt.month
df["day"] = df["date"].dt.day
df["weekday"] = df["date"].dt.dayofweek
df["hour"] = df["date"].dt.hour

In [9]:
df["is_weekend"] = df["weekday"].isin([5, 6]).astype(int)

In [10]:
df.head()

,date,category,amount,year,month,day,weekday,hour,is_weekend
0,2022-07-06 05:57:10+00:00,Restuarant,5.50,2022,7,6,2,5,0
1,2022-07-06 05:57:27+00:00,Market,2.00,2022,7,6,2,5,0
2,2022-07-06 05:58:12+00:00,Coffe,30.10,2022,7,6,2,5,0
3,2022-07-06 05:58:25+00:00,Market,17.33,2022,7,6,2,5,0
4,2022-07-06 05:59:00+00:00,Restuarant,5.50,2022,7,6,2,5,0

In [11]:
df["date"] = pd.to_datetime(df["date"])

df["year"] = df["date"].dt.year
df["month"] = df["date"].dt.month
df["day"] = df["date"].dt.day
df["weekday"] = df["date"].dt.dayofweek
df["hour"] = df["date"].dt.hour
df["is_weekend"] = df["weekday"].isin([5,6]).astype(int)

df.head()

,date,category,amount,year,month,day,weekday,hour,is_weekend
0,2022-07-06 05:57:10+00:00,Restuarant,5.50,2022,7,6,2,5,0
1,2022-07-06 05:57:27+00:00,Market,2.00,2022,7,6,2,5,0
2,2022-07-06 05:58:12+00:00,Coffe,30.10,2022,7,6,2,5,0
3,2022-07-06 05:58:25+00:00,Market,17.33,2022,7,6,2,5,0
4,2022-07-06 05:59:00+00:00,Restuarant,5.50,2022,7,6,2,5,0

In [12]:
from sklearn.preprocessing import LabelEncoder

encoder = LabelEncoder()

df["category"] = encoder.fit_transform(df["category"])

df.head()

,date,category,amount,year,month,day,weekday,hour,is_weekend
0,2022-07-06 05:57:10+00:00,14,5.50,2022,7,6,2,5,0
1,2022-07-06 05:57:27+00:00,9,2.00,2022,7,6,2,5,0
2,2022-07-06 05:58:12+00:00,2,30.10,2022,7,6,2,5,0
3,2022-07-06 05:58:25+00:00,9,17.33,2022,7,6,2,5,0
4,2022-07-06 05:59:00+00:00,14,5.50,2022,7,6,2,5,0

In [13]:
X = df.drop(columns=["date","amount"])

y = df["amount"]

X.head()

   category  year  month  day  weekday  hour  is_weekend
0        14  2022      7    6        2     5           0
1         9  2022      7    6        2     5           0
2         2  2022      7    6        2     5           0
3         9  2022      7    6        2     5           0
4        14  2022      7    6        2     5           0

In [14]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [15]:
from sklearn.ensemble import RandomForestRegressor

model = RandomForestRegressor(
    n_estimators=100,
    random_state=42
)

model.fit(X_train,y_train)

RandomForestRegressor(random_state=42)

In [16]:
prediction = model.predict(X_test)

prediction[:10]

array([ 6.8876    ,  7.66      ,  4.4517    , 12.367     ,  3.08076667,
        2.64      , 10.2       ,  1.06275   , 15.5784    , 30.4214    ])

In [17]:
from sklearn.metrics import mean_absolute_error,r2_score

mae = mean_absolute_error(y_test,prediction)

r2 = r2_score(y_test,prediction)

print("MAE :",mae)

print("R2 :",r2)

MAE : 10.20152817753623
R2 : 0.23888150821817578

In [18]:
import joblib

joblib.dump(
    model,
    "../app/ml/models/spending_model.pkl"
)

joblib.dump(
    encoder,
    "../app/ml/models/category_encoder.pkl"
)

['../app/ml/models/category_encoder.pkl']

In [19]:
loaded_model = joblib.load(
    "../app/ml/models/spending_model.pkl"
)

loaded_model

RandomForestRegressor(random_state=42)